Repository jv-kune-kune/PiglioTech-BackEnd, pull requests merged in 2025-01, with the labels that each got.

#19 Create sync-labels.yml
  .github/workflows /sync-labels.yml
Labels: 👥 project management 📋

#23 Region parametric requests
  pom.xml
  src/main/java/org/kunekune/PiglioTech/controller/UserController.java
  src/main/java/org/kunekune/PiglioTech/model/Book.java
  src/main/java/org/kunekune/PiglioTech/model/GoogleResult.java
  src/main/java/org/kunekune/PiglioTech/repository/GoogleBooksDAO.java
  src/main/java/org/kunekune/PiglioTech/repository/UserRepository.java
  src/main/java/org/kunekune/PiglioTech/service/BookService.java
  src/main/java/org/kunekune/PiglioTech/service/BookServiceImpl.java
  src/main/java/org/kunekune/PiglioTech/service/UserService.java
  src/main/java/org/kunekune/PiglioTech/service/UserServiceImpl.java
  src/test/java/org/kunekune/PiglioTech/controller/UserControllerTest.java
  src/test/java/org/kunekune/PiglioTech/model/GoogleResultTest.java
  src/test/java/org/kunekune/PiglioTech/repository/GoogleBooksDaoTest.java
  src/test/java/org/kunekune/PiglioTech/repository/TestStrings.java
  src/test/java/org/kunekune/PiglioTech/service/BookServiceTest.java
  src/test/java/org/kunekune/PiglioTech/service/UserServiceTest.java
Labels: 🏷️ error handling 🛑, 🏷️ testing 🔍, 🏷️ api 🔗

#39 feat: add addition controller endpoints and serivce layer imp (alternate work)
  src/main/java/org/kunekune/PiglioTech/controller/BookController.java
  src/main/java/org/kunekune/PiglioTech/controller/UserController.java
  src/main/java/org/kunekune/PiglioTech/exception/ApiServiceException.java
  src/main/java/org/kunekune/PiglioTech/exception/GlobalExceptionHandler.java
  src/main/java/org/kunekune/PiglioTech/repository/BookRepository.java
  src/main/java/org/kunekune/PiglioTech/repository/UserRepository.java
  src/main/java/org/kunekune/PiglioTech/service/BookService.java
  src/main/java/org/kunekune/PiglioTech/service/BookServiceImpl.java
  src/main/java/org/kunekune/PiglioTech/service/UserService.java
  src/main/java/org/kunekune/PiglioTech/service/UserServiceImpl.java
  src/test/java/org/kunekune/PiglioTech/controller/UserControllerTest.java
Labels: 🚩 duplicate 🔁, 🏷️ api 🔗, 👥 backend 🛠️

#42 feat: User Book Management and API Enhancements
  src/main/java/org/kunekune/PiglioTech/controller/BookController.java
  src/main/java/org/kunekune/PiglioTech/controller/UserController.java
  src/main/java/org/kunekune/PiglioTech/exception/ApiServiceException.java
  src/main/java/org/kunekune/PiglioTech/exception/GlobalExceptionHandler.java
  src/main/java/org/kunekune/PiglioTech/repository/BookRepository.java
  src/main/java/org/kunekune/PiglioTech/repository/UserRepository.java
  src/main/java/org/kunekune/PiglioTech/service/BookService.java
  src/main/java/org/kunekune/PiglioTech/service/BookServiceImpl.java
  src/main/java/org/kunekune/PiglioTech/service/UserService.java
  src/main/java/org/kunekune/PiglioTech/service/UserServiceImpl.java
  src/test/java/org/kunekune/PiglioTech/controller/UserControllerTest.java
  src/test/java/org/kunekune/PiglioTech/service/UserServiceTest.java
Labels: 🏷️ api 🔗, 👥 backend 🛠️

#43 15 ci cicd initial setup
  .DS_Store
  .github/.DS_Store
  .github/workflows/ci.yml
  checkstyle.xml
  eclipse-java-google-style.xml
  heroku.yml
  pom.xml
  src/.DS_Store
  src/main/.DS_Store
Labels: 🏷️ devops ⚙️

#44 ci: Making fixes for Sonar
  src/main/java/org/kunekune/PiglioTech/service/BookServiceImpl.java
  src/test/java/org/kunekune/PiglioTech/model/GoogleResultTest.java
  src/test/java/org/kunekune/PiglioTech/service/UserServiceTest.java
Labels: 🏷️ devops ⚙️

#45 ci: add permissions block to GitHub Actions workflow
  .github/workflows/ci.yml
Labels: 🏷️ devops ⚙️

#46 ci: update dependency review step to use correct token and handle pull request events
  .github/workflows/ci.yml
Labels: 🏷️ devops ⚙️, 👥 backend 🛠️

#50 ci: cicd-initial-setup-revisions-4
  .github/ci-README.md
  .github/workflows-README.md
  .github/workflows/ci.yml
  pom.xml
Labels: 🏷️ devops ⚙️

#55 style: apply Spotless fixes to entire codebase
  src/main/java/org/kunekune/PiglioTech/PiglioTechApplication.java
  src/main/java/org/kunekune/PiglioTech/controller/BookController.java
  src/main/java/org/kunekune/PiglioTech/controller/SwapController.java
  src/main/java/org/kunekune/PiglioTech/controller/UserController.java
  src/main/java/org/kunekune/PiglioTech/exception/ApiServiceException.java
  src/main/java/org/kunekune/PiglioTech/exception/GlobalExceptionHandler.java
  src/main/java/org/kunekune/PiglioTech/model/Book.java
  src/main/java/org/kunekune/PiglioTech/model/Match.java
  src/main/java/org/kunekune/PiglioTech/model/Region.java
  src/main/java/org/kunekune/PiglioTech/model/SwapRequest.java
  src/main/java/org/kunekune/PiglioTech/model/User.java
  src/main/java/org/kunekune/PiglioTech/repository/GoogleBooksDAO.java
  src/main/java/org/kunekune/PiglioTech/repository/MatchRepository.java
  src/main/java/org/kunekune/PiglioTech/repository/SwapRequestRepository.java
  src/main/java/org/kunekune/PiglioTech/repository/UserRepository.java
  src/main/java/org/kunekune/PiglioTech/service/BookService.java
  src/main/java/org/kunekune/PiglioTech/service/BookServiceImpl.java
  src/main/java/org/kunekune/PiglioTech/service/SwapService.java
  src/main/java/org/kunekune/PiglioTech/service/SwapServiceImpl.java
  src/main/java/org/kunekune/PiglioTech/service/UserService.java
  src/main/java/org/kunekune/PiglioTech/service/UserServiceImpl.java
  src/main/java/org/kunekune/PiglioTech/util/SwapConverters.java
  src/test/java/org/kunekune/PiglioTech/PiglioTechApplicationTests.java
  src/test/java/org/kunekune/PiglioTech/controller/BookControllerTest.java
  src/test/java/org/kunekune/PiglioTech/controller/SwapControllerTest.java
  src/test/java/org/kunekune/PiglioTech/controller/UserControllerTest.java
  src/test/java/org/kunekune/PiglioTech/exception/ApiServiceExceptionTest.java
  src/test/java/org/kunekune/PiglioTech/exception/GlobalExceptionHandlerTest.java
  src/test/java/org/kunekune/PiglioTech/model/GoogleResultTest.java
  src/test/java/org/kunekune/PiglioTech/repository/GoogleBooksDaoTest.java
  src/test/java/org/kunekune/PiglioTech/repository/TestStrings.java
  src/test/java/org/kunekune/PiglioTech/service/BookServiceTest.java
  src/test/java/org/kunekune/PiglioTech/service/SwapServiceTest.java
  src/test/java/org/kunekune/PiglioTech/service/UserServiceTest.java
  src/test/java/org/kunekune/PiglioTech/util/SwapConvertersTest.java
Labels: 🏷️ error handling 🛑, 🏷️ testing 🔍
